name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      RELEASE_FILE: target/release/numlock-toggle

    steps:
    - uses: actions/checkout@v4
    - name: Install libudev
      run: sudo apt-get install -y libudev-dev
    - name: Build
      run: cargo build --verbose
    - name: Rename with Version & Platform
      if: github.ref_type == 'tag'
      run: mv ${{ env.RELEASE_FILE }} ${{ env.RELEASE_FILE }}_${{ github.ref_name }}
    - name: Publish
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.RELEASE_FILE }}_${{ github.ref_name }}
