name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      RELEASE_FILE: target/release/numlock-toggle

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Publish
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.RELEASE_FILE }}_${{ github.ref_name }}
